### ISSUE TITLE
How to specify environment variables

### ISSUE THREAD

**Issue by shinka81** [dcos/metronome#103]
How should we specify environment variables for docker containers? I have tried the following job config and attempted to create a job in the web UI and the DCOS cli but it doesn't seem to persist my env config, it just removes it.

```
{
  "id": "test",
  "run": {
    "cpus": 0.01,
    "mem": 32,
    "disk": 0,
    "env": {
        "foo": "bar"
    },
    "docker": {
      "image": "busybox"
    }
  },
  "schedules": []
}
```

**Comment by tobilg** [comment]
Have you seen the example at https://github.com/dcos/metronome/blob/master/api/src/main/resources/public/api/v1/examples/job.json

**Comment by shinka81** [comment]
@tobilg thanks for pointing me to that, it wasn't obvious on the DCOS website where the more verbose examples were. But looking at the example, it seems that my above config matches the given example for env var's. But within the DC/OS job UI it still does not show my environment variables in the job's json object.

**Comment by tobilg** [comment]
Sorry @shinka81, can you please elaborate? The 1.8.6 DC/OS UI doesn't even see to allow the entering of env vars in the non-JSON mode. Could you please show the JSON you tried to pass via the `dcos job add` command?

**Comment by shinka81** [comment]
@tobilg it seems that using the cli does respect the `env` key so that answers my question. So the 1.8.6 DC/OS UI does not support showing any key that is not a field in the non-json mode? For example, I can see my env key in the cli but not in the UI when I click JSON mode.

This issue can be closed as I think my question has been answered, thanks @tobilg !

**Comment by tobilg** [comment]
@shinka81 You can close the issue yourself if you think it's solved.
