### ISSUE TITLE
Job name regex

### ISSUE THREAD

**Issue by bydga** [dcos/metronome#106]
Is there a reason, why the regex for job name is so strict? if you take in mind that Marathon allows slashes as a "group" delimiter, metronome has nothing similar (and dashes are widely used in project names on github/gitlab etc.)

Having at least one special symbol to be able to distinguish individual parts of the job name would be highly appreciated.

I.e: we are deploying projects with pattern like: `$repository/$project-name/$environment/$unit-name`. If we use dashes as delimiters, we wouldnt be able to recreate the original "path"..

**Comment by aquamatthias** [comment]
Hey @bydga 
Marathon uses ids with slashes. This leads to unintuitive url schemas.
We decided to use the package syntax for metronome.
So instead of `/some/nested/path` you would use `some.nested.path`
