### ISSUE TITLE
Chronos  successor?

### ISSUE THREAD

**Issue by kamilchm** [dcos/metronome#90]
Hi,

do you plan to replace Chronos with Metronome?
We are looking for a job scheduling framework and I wonder if it's better to go with Chronos or be an early adopter of Metronome?

**Comment by brat002** [comment]
Chronos is terrible and contains lot of bugs. We tired with it. Maybe metronome will be better.

**Comment by kamilchm** [comment]
Anyone interested in running http://dkron.io/ on Mesos?

**Comment by brat002** [comment]
Anything will better than Chronos.

**Comment by cmaloney** [comment]
Metronome is the successor for Chronos within DC/OS, and definitely can be used outside of DC/OS. The UI is part of the DC/OS UI currently, but just the API would likely be better than Chronos. Be happy to see someone make a just-metronome UI outside of DC/OS as well. The UI is all driven by the metronome API.

**Comment by tobilg** [comment]
There's a Dockerfile project at https://github.com/mesoshq/metronome to be able to use it in plain Mesos clusters. In fact, I started to build an non-DC/OS UI, but it's not finished yet.
